export const TIMEZONES = [
  { id: "Europe/Kaliningrad", label: "Калининград (UTC+2)" },
  { id: "Europe/Moscow", label: "Москва (UTC+3)" },
  { id: "Europe/Samara", label: "Самара (UTC+4)" },
  { id: "Asia/Yekaterinburg", label: "Екатеринбург (UTC+5)" },
  { id: "Asia/Omsk", label: "Омск (UTC+6)" },
  { id: "Asia/Novosibirsk", label: "Новосибирск (UTC+7)" },
  { id: "Asia/Krasnoyarsk", label: "Красноярск (UTC+7)" },
  { id: "Asia/Irkutsk", label: "Иркутск (UTC+8)" },
  { id: "Asia/Yakutsk", label: "Якутск (UTC+9)" },
  { id: "Asia/Vladivostok", label: "Владивосток (UTC+10)" },
  { id: "Asia/Magadan", label: "Магадан (UTC+11)" },
  { id: "Asia/Kamchatka", label: "Камчатка (UTC+12)" },
  { id: "Asia/Almaty", label: "Алматы" },
  { id: "Asia/Tashkent", label: "Ташкент (UTC+5)" },
  { id: "Asia/Tbilisi", label: "Тбилиси (UTC+4)" },
  { id: "Asia/Yerevan", label: "Ереван (UTC+4)" },
  { id: "Europe/Minsk", label: "Минск (UTC+3)" },
  { id: "Asia/Dubai", label: "Дубай (UTC+4)" },
] as const;
